name: al_faruk_app
description: Al Faruk Multimedia Production App.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Utility Packages
  google_fonts: ^6.1.0         # For custom fonts like 'Inter'
  permission_handler: ^11.3.1
  # Feature Packages
  pinput: ^3.0.1               # For the OTP screen
  #youtube_player_flutter: ^9.0.1 # For the video player
  flutter_qiblah: ^3.1.0    # For Qiblah direction feature
  geolocator: ^13.0.4
  geocoding: ^2.1.0
  adhan: ^2.0.0+1
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  youtube_player_iframe: ^5.1.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2 
  flutter_localizations_plus: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  generate: true

  uses-material-design: true

  # Register asset folder
  assets:
    - .env
    - assets/images/logo.png 
    - assets/images/logo_symbol.png
    - assets/images/thumb_islamic_art.png
    - assets/images/thumb_baghdad.png
    - assets/images/thumb_calligraphy.png
    - assets/audio/adhan.mp3
    - assets/audio/takbir.mp3
    - assets/audio/tone.mp3
    - assets/icons/google.png
    - assets/icons/facebook.png
